# Generated by Django 4.1.7 on 2023-03-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexcalculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionstrategydup',
            name='calc_itc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategydup',
            name='cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategydup',
            name='cash_in_hand',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategydup',
            name='days_from_today',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategydup',
            name='default_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategydup',
            name='extra_cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategydup',
            name='risk_free_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
