# Generated by Django 4.1.7 on 2023-04-12 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invexcalculator', '0003_alter_optionstrategypositiondup_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionstrategydup',
            name='current_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='optionstrategydup',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optionstrategypositiondup',
            name='buysell',
            field=models.CharField(blank=True, choices=[('but', 'Buy'), ('sell', 'Sell')], max_length=10),
        ),
        migrations.AlterField(
            model_name='optionstrategypositiondup',
            name='callput',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('put', 'Put')], max_length=10),
        ),
    ]
